### ISSUE TITLE
Seeing error when running fresh clone ObjectMiddleware.register: serializer for mini-css-extract-plugin is already registered error 

### ISSUE THREAD

**Issue by fvarga01** [stackrole/gatsby-starter-foundation#27]
Seeing error when trying to run a freshly downloaded copy of the source:
Error: ObjectMiddleware.register: serializer for mini-css-extract-plugin/dist/CssModule/null is already registered

Steps to repro:
=========
gatsby new gatsby-starter-foundation https://github.com/stackrole/gatsby-starter-foundation
cd gatsby-starter-foundation 
gatsby develop

Environment:
=========
Windows 10
gatsby --version:
   Gatsby CLI version: 3.4.0
   Gatsby version: 3.4.1   Note: this is the Gatsby version for the site at: C:\sourcerepo\gatsby-starter-foundation
npm --version 
  6.14.8
git --version
   git version 2.31.1.windows.1

Troubleshooting Done
==================
deleted node_modules folder
deleted package-lock.json
Cleared caches
   gatsby clean
  npm cache clear --force
Rebooted the machine
I can run other gatsby starters without issue

Raw Output:
=========
C:\sourcerepo\gatsby-starter-foundation>gatsby develop
info

There are 6 other flags available that you might be interested in:
- FAST_DEV · Enable all experiments aimed at improving develop server start time
- DEV_SSR · (Umbrella Issue (https://gatsby.dev/dev-ssr-feedback)) · Server Side Render (SSR) pages on full reloads during develop. Helps you detect SSR bugs and fix them without needing to do full builds.
- PRESERVE_WEBPACK_CACHE · (Umbrella Issue (https://gatsby.dev/cache-clearing-feedback)) · Use webpack's persistent caching and don't delete webpack's cache when changing gatsby-node.js & gatsby-config.js
files.
- PRESERVE_FILE_DOWNLOAD_CACHE · (Umbrella Issue (https://gatsby.dev/cache-clearing-feedback)) · Don't delete the downloaded files cache when changing gatsby-node.js & gatsby-config.js files.
- PARALLEL_SOURCING · EXPERIMENTAL · (Umbrella Issue (https://gatsby.dev/parallel-sourcing-feedback)) · Run all source plugins at the same time instead of serially. For sites with multiple source plugins, this
 can speedup sourcing and transforming considerably.
- FUNCTIONS · EXPERIMENTAL · (Umbrella Issue (https://gatsby.dev/functions-feedback)) · Compile Serverless functions in your Gatsby project and write them to disk, ready to deploy to Gatsby Cloud

success open and validate gatsby-configs - 0.307s
success load plugins - 2.750s
success onPreInit - 0.055s
success initialize cache - 0.012s
success copy gatsby files - 0.349s
success onPreBootstrap - 0.045s
success createSchemaCustomization - 0.100s
success Checking for changed pages - 0.003s
success source and transform nodes - 0.703s
success building schema - 1.229s
success createPages - 0.165s
success createPagesStatefully - 0.131s
info Total nodes: 143, SitePage nodes: 19 (use --verbose for breakdown)
success Checking for changed pages - 0.001s
success update schema - 0.138s
success write out redirect data - 0.003s
success Build manifest and related icons - 0.108s
success onPostBootstrap - 0.118s
info bootstrap finished - 10.115s
success onPreExtractQueries - 0.002s
success extract queries from components - 2.341s
success write out requires - 0.108s
success run static queries - 0.064s - 3/3 47.03/s
success run page queries - 3.684s - 3/3 0.81/s

 ERROR

ObjectMiddleware.register: serializer for mini-css-extract-plugin/dist/CssModule/null is already registered

  Error: ObjectMiddleware.register: serializer for mini-css-extract-plugin/dist/CssModule/null is already registered

  - ObjectMiddleware.js:182 Object.register
    [gatsby-starter-foundation]/[webpack]/lib/serialization/ObjectMiddleware.js:182:10

  - index.js:163 Function.getCssModule
    [gatsby-starter-foundation]/[mini-css-extract-plugin]/dist/index.js:163:34

  - index.js:371 MiniCssExtractPlugin.apply
    [gatsby-starter-foundation]/[mini-css-extract-plugin]/dist/index.js:371:44

  - webpack.js:74 createCompiler
    [gatsby-starter-foundation]/[webpack]/lib/webpack.js:74:12

  - webpack.js:123 create
    [gatsby-starter-foundation]/[webpack]/lib/webpack.js:123:16

  - webpack.js:147 webpack
    [gatsby-starter-foundation]/[webpack]/lib/webpack.js:147:32

  - index.js:54 f
    [gatsby-starter-foundation]/[webpack]/lib/index.js:54:15

  - start-server.ts:164 startServer
    [gatsby-starter-foundation]/[gatsby]/src/utils/start-server.ts:164:20

  - task_queues.js:62 runNextTicks
    internal/process/task_queues.js:62:5

  - timers.js:434 processImmediate
    internal/timers.js:434:9

  - start-webpack-server.ts:44 startWebpackServer
    [gatsby-starter-foundation]/[gatsby]/src/services/start-webpack-server.ts:44:7

not finished Building development bundle - 7.416s

**Comment by munwr** [comment]
This is caused due to a recent update in Netlify CMS and related plugins.

Please try deleting you node_modules and try "yarn install"

This should fix the issue. Before 

![image](https://user-images.githubusercontent.com/6573105/117346881-f8bf2980-aec5-11eb-92c3-96dbdbbe067d.jpeg)

installing packages make sure you don't have caret ^ character before the version number.  Refer attached image
.


Thank you for using Foundation 😊

**Comment by fvarga01** [comment]
I get the same error when deleting node_modules and "yarn install", followed by "gatsby develop".

 What do you by "installing packages make sure you don't have caret ^ character before the version number." 

Do you mean I should remove the caret from EVERY  line under the "dependencies" section or just the ones with **netlify-cms** in the name?

This is what I currently have:
![image](https://user-images.githubusercontent.com/14260028/117360315-3f893100-ae7e-11eb-9080-e0536e620ba1.png)

**Comment by fvarga01** [comment]
I got this working as follows:

1. gatsby new gatsby-starter-foundation https://github.com/stackrole/gatsby-starter-foundation
2. cd gatsby-starter-foundation
3. Per your suggestion, I edited the package.json file and removed the caret character from EVERY LINE (if I only removed from lines with netlify-cms in the name I still got the same error)
![image](https://user-images.githubusercontent.com/14260028/117362339-bf17ff80-ae80-11eb-9c52-92941fe52fba.png)
4. yarn install (instead of npm install)
5. gatsby develop

It now succeeds. I will plan on deploying this to Github Pages, so I'm hoping the updated package.json will be enough for github pages to build correctly.

Thanks for your assistance with this issue.

**Comment by liminalfun** [comment]
I followed the steps as suggested and still receiving error messages when running `gatsby develop`.

**Steps**
1. Delete node_modules
2. Remove the caret character from every line of package.json
3. yarn install
4. gatsby develop

**Error Message**

The 'compilation' argument must be an instance
of Compilation


  TypeError: The 'compilation' argument must be 
  an instance of Compilation
  
  - NormalModule.js:195 Function.getCompilationH
    ooks
    [subversions]/[webpack]/lib/NormalModule.js:
    195:10
  
  - index.js:253 
    [subversions]/[@pmmmwh]/react-refresh-webpac
    k-plugin/lib/index.js:253:26
  
  
  - Hook.js:14 Hook.CALL_DELEGATE [as _call]
    [subversions]/[tapable]/lib/Hook.js:14:14
  
  - Compiler.js:1031 Compiler.newCompilation
    [subversions]/[gatsby-plugin-netlify-cms]/[w
    ebpack]/lib/Compiler.js:1031:26
  
  - Compiler.js:1073 
    [subversions]/[gatsby-plugin-netlify-cms]/[w
    ebpack]/lib/Compiler.js:1073:29
  
  
  - Hook.js:18 Hook.CALL_ASYNC_DELEGATE [as _cal
    lAsync]
    [subversions]/[tapable]/lib/Hook.js:18:14
  
  - Compiler.js:1068 Compiler.compile
    [subversions]/[gatsby-plugin-netlify-cms]/[w
    ebpack]/lib/Compiler.js:1068:28
  
  - Watching.js:134 
    [subversions]/[gatsby-plugin-netlify-cms]/[w
    ebpack]/lib/Watching.js:134:19
  
  
  - runMicrotasks
  
  - task_queues.js:93 processTicksAndRejections
    internal/process/task_queues.js:93:5
  

not finished Building development bundle -
7.161s



Looks like a great starter, but unfortunately I'll be switching to something else. Hope you're able to resolve the issue! :)

**Comment by NaturallyAsh** [comment]
This might help someone. I updated to npm 7, which messed up all my peer dependencies. Running `npm install --legacy-peer-deps` fixed the problem. Gatsby docs say to install this way for the time being.

**Comment by apoorvachikara** [comment]
> I got this working as follows:
> 
> 1. gatsby new gatsby-starter-foundation https://github.com/stackrole/gatsby-starter-foundation
> 2. cd gatsby-starter-foundation
> 3. Per your suggestion, I edited the package.json file and removed the caret character from EVERY LINE (if I only removed from lines with netlify-cms in the name I still got the same error)
>    ![image](https://user-images.githubusercontent.com/14260028/117362339-bf17ff80-ae80-11eb-9c52-92941fe52fba.png)
> 4. yarn install (instead of npm install)
> 5. gatsby develop
> 
> It now succeeds. I will plan on deploying this to Github Pages, so I'm hoping the updated package.json will be enough for github pages to build correctly.
> 
> Thanks for your assistance with this issue.

I followed the same steps with Node version v14, but I have received an error:

```
 gatsby develop
success open and validate gatsby-configs - 0.209s
warn Plugin gatsby-remark-images is not compatible with your gatsby version 3.1.2 - It requires gatsby@^4.0.0-next
success load plugins - 2.313s
success onPreInit - 0.076s
success initialize cache - 0.016s
success copy gatsby files - 0.157s
success onPreBootstrap - 0.034s
success createSchemaCustomization - 0.079s
success Checking for changed pages - 0.002s
success source and transform nodes - 0.398s
success building schema - 0.804s
info Total nodes: 139, SitePage nodes: 16 (use --verbose for breakdown)
success createPages - 0.120s
success Checking for changed pages - 0.001s
success createPagesStatefully - 0.102s
success update schema - 0.105s
success write out redirect data - 0.003s
success Build manifest and related icons - 0.228s
success onPostBootstrap - 0.236s
info bootstrap finished - 7.830s
success onPreExtractQueries - 0.002s
success extract queries from components - 1.712s
success write out requires - 0.016s
success run static queries - 0.048s - 3/3 62.57/s
success run page queries - 1.618s - 3/3 1.85/s

 ERROR 

Invalid options object. Ignore Plugin has been initialized using an options object that does not match the API schema.
 - options should be one of these:
   object { resourceRegExp, contextRegExp? } | object { checkResource }
   Details:
    * options misses the property 'resourceRegExp'. Should be:
      RegExp
      -> A RegExp to test the request against.
    * options misses the property 'checkResource'. Should be:
      function
      -> A filter function for resource and context.



  ValidationError: Invalid options object. Ignore Plugin has been initialized using an options object that does not match the API schema.
   - options should be one of these:
     object { resourceRegExp, contextRegExp? } | object { checkResource }
     Details:
      * options misses the property 'resourceRegExp'. Should be:
        RegExp
        -> A RegExp to test the request against.
      * options misses the property 'checkResource'. Should be:
        function
        -> A filter function for resource and context.
  
  - validate.js:105 validate
    [gatsby-starter-foundation]/[schema-utils]/dist/validate.js:105:11
  
  - create-schema-validation.js:16 
    [gatsby-starter-foundation]/[webpack]/lib/util/create-schema-validation.js:16:17
  
  - IgnorePlugin.js:28 new IgnorePlugin
    [gatsby-starter-foundation]/[webpack]/lib/IgnorePlugin.js:28:3
  
  - webpack-plugins.ts:14 Object.ignore
    [gatsby-starter-foundation]/[gatsby]/src/utils/webpack-plugins.ts:14:10
  
  - webpack-utils.ts:766 Object.moment
    [gatsby-starter-foundation]/[gatsby]/src/utils/webpack-utils.ts:766:42
  
  - webpack.config.js:200 getPlugins
    [gatsby-starter-foundation]/[gatsby]/src/utils/webpack.config.js:200:15
  
  - webpack.config.js:491 module.exports
    [gatsby-starter-foundation]/[gatsby]/src/utils/webpack.config.js:491:14
  
  - build-html.ts:139 buildRenderer
    [gatsby-starter-foundation]/[gatsby]/src/commands/build-html.ts:139:18
  
  - start-server.ts:113 createIndexHtml
    [gatsby-starter-foundation]/[gatsby]/src/utils/start-server.ts:113:28
  
  - start-server.ts:150 startServer
    [gatsby-starter-foundation]/[gatsby]/src/utils/start-server.ts:150:5
  
  - start-webpack-server.ts:44 startWebpackServer
    [gatsby-starter-foundation]/[gatsby]/src/services/start-webpack-server.ts:44:7
  

not finished Building development bundle - 0.127s
```

How can I solve it? It seems ifI install dependencies using npm there is a different error. How can I solve them? Are there any steps to follow?
